import Vue from 'vue';
import VditorPreview from 'vditor/dist/method.min';

import Vditor from 'vditor';


let emoji = {
  "+1":                                   "👍",
  "-1":                                   "👎",
  "100":                                  "💯",
  "Accept":                               "🉑",
  "beer":                                 "🍺",
  "bug":                                  "🐛",
  "bulb":                                 "💡",
  "computer":                             "💻",
  "construction":                         "🚧",
  "construction_worker":                  "👷",
  "construction_worker_man":              "👷",
  "construction_worker_woman":            "👷‍♀",
  "face_with_head_bandage":               "🤕",
  "face_with_thermometer":                "🤒",
  "fearful":                              "😨",
  "flushed":                              "😳",
  "frowning":                             "😦",
  "frowning_face":                        "☹️",
  "full_moon_with_face":                  "🌝",
  "grimacing":                            "😬",
  "grin":                                 "😁",
  "grinning":                             "😀",
  "hankey":                               "💩",
  "metal":                                "🤘",
  "money_mouth_face":                     "🤑",
  "nerd_face":                            "🤓",
  "neutral_face":                         "😐",
  "persevere":                            "😣",
  "point_down":                           "👇",
  "point_left":                           "👈",
  "point_right":                          "👉",
  "point_up_2":                           "👆",
  "satisfied":                            "😆",
  "sleeping":                             "😴",
  "sleepy":                               "😪",
  "slightly_frowning_face":               "🙁",
  "slightly_smiling_face":                "🙂",
  "smile":                                "😄",
  "smiley":                               "😃",
  "smiling_imp":                          "😈",
  "smirk":                                "😏",
  "sneezing_face":                        "🤧",
  "sob":                                  "😭",
  "sparkler":                             "🎇",
  "sparkles":                             "✨",
  "stopwatch":                            "⏱",
  "strawberry":                           "🍓",
  "stuck_out_tongue":                     "😛",
  "stuck_out_tongue_closed_eyes":         "😝",
  "stuck_out_tongue_winking_eye":         "😜",
  "sun_behind_large_cloud":               "🌥",
  "sun_behind_rain_cloud":                "🌦",
  "sun_behind_small_cloud":               "🌤",
  "sun_with_face":                        "🌞",
  "sunflower":                            "🌻",
  "sunglasses":                           "😎",
  "sweat":                                "😓",
  "sweat_smile":                          "😅",
  "unamused":                             "😒",
  "unlock":                               "🔓",
  "upside_down_face":                     "🙃",
  "v":                                    "✌️",
  "wink":                                 "😉",
  "wrench":                               "🔧",
  "writing_hand":                         "✍️",
  "x":                                    "❌",
  "yellow_heart":                         "💛",
  "zipper_mouth_face":                    "🤐",
  "zzz":                                  "💤"
}


Vue.emoji = emoji
Vue.VditorPreview = VditorPreview;
Vue.Vditor = Vditor
