name: deploy
on: [release]
jobs:
  build:
    name: building
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
      - run: npm install
      - run: npm run build
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: ".nuxt"
          target: ${{ secrets.REMOTE_TARGET}}
      - uses: MrSquaare/ssh-setup-action@v1.0.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          private-key: ${{ secrets.SERVER_SSH_KEY }}
      - run: ~/build.sh
